{{
   const btoa = require('btoa');
   const btoastring = `${REACTORY_APPLICATION_EMAIL}:${REACTORY_APPLICATION_PASSWORD}`;
   exports.authToken = btoa(btoastring);
}}
POST http://localhost:4000/login HTTP/1.1
Content-Type: application/json
Accept: application/json
x-client-key: {{REACTORY_CLIENT_KEY}}
x-client-secret: {{REACTORY_CLIENT_PWD}}
Authorization: Basic {{authToken}}

{{
   const { token } = response.parsedBody.user;
   exports.jwtToken = token;
}}

HTTP/1.1 401  - Unauthorized
x-powered-by: Express
vary: Origin
access-control-allow-credentials: true
access-control-expose-headers: X-Client-Key,X-Client-Pwd,x-client-key,x-client-pwd,x-client-version,x-client-name
content-type: application/json; charset=utf-8
content-length: 31
etag: W/"1f-sMAi1XfEJKDPV9ajpjCQqYQmOuM"
date: Wed, 26 Mar 2025 23:46:19 GMT
connection: close
###
GET http://localhost:4000/support/tickets
Accept: text/html
x-client-key: {{REACTORY_CLIENT_KEY}}
x-client-secret: {{REACTORY_CLIENT_PWD}}
Authorization: Bearer {{jwtToken}}