query Lasec360UserList($search: Lasec360UserSearch) {
  LasecGetRemoteUsers(search: $search) {
    id
    code
    repId
    firstName
    lastName
    email
    roles
    target
    targetPercent
  }
}