export const InvoiceFilterByEnumsKeys = {
  any_field: 'any_field',
  date_range: 'date_range',
  invoice_date: 'invoice_date',
  invoice_number: 'invoice_number',
  po_number: 'po_number',
  invoice_value: 'invoice_value',
  // mup_perc: 'mup_perc',
  // gp_perc: 'gp_perc',
  account_number: 'account_number',
  customer: 'customer',
  client: 'client',
  dispatch_number: 'dispatch_number',
  iso_number: 'iso_number',
  quote_number: 'quote_number',
  sales_team_id: 'sales_team_id',
};

export const InvoiceFilterByEnumArray: string[] = [
  InvoiceFilterByEnumsKeys.any_field,
  InvoiceFilterByEnumsKeys.date_range,
  InvoiceFilterByEnumsKeys.invoice_date,
  InvoiceFilterByEnumsKeys.invoice_number,
  InvoiceFilterByEnumsKeys.po_number,
  InvoiceFilterByEnumsKeys.invoice_value,
  // InvoiceFilterByEnumsKeys.mup_perc,
  // InvoiceFilterByEnumsKeys.gp_perc,
  InvoiceFilterByEnumsKeys.account_number,
  InvoiceFilterByEnumsKeys.customer,
  InvoiceFilterByEnumsKeys.client,
  InvoiceFilterByEnumsKeys.dispatch_number,
  InvoiceFilterByEnumsKeys.iso_number,
  InvoiceFilterByEnumsKeys.quote_number,
  InvoiceFilterByEnumsKeys.sales_team_id,
];

export const InvoiceFilterByOptions = [
  { key: InvoiceFilterByEnumsKeys.any_field, value: InvoiceFilterByEnumsKeys.any_field, label: 'All Categories' },
  { key: InvoiceFilterByEnumsKeys.date_range, value: InvoiceFilterByEnumsKeys.date_range, label: 'Date Range' },
  { key: InvoiceFilterByEnumsKeys.invoice_date, value: InvoiceFilterByEnumsKeys.invoice_date, label: 'Invoice Date' },
  { key: InvoiceFilterByEnumsKeys.invoice_number, value: InvoiceFilterByEnumsKeys.invoice_number, label: 'Invoice Number' },
  { key: InvoiceFilterByEnumsKeys.po_number, value: InvoiceFilterByEnumsKeys.po_number, label: 'PO Number' },
  { key: InvoiceFilterByEnumsKeys.invoice_value, value: InvoiceFilterByEnumsKeys.invoice_value, label: 'Invoice Value' },
  // { key: InvoiceFilterByEnumsKeys.mup_perc, value: InvoiceFilterByEnumsKeys.mup_perc, label: 'MUP%' },
  // { key: InvoiceFilterByEnumsKeys.gp_perc, value: InvoiceFilterByEnumsKeys.gp_perc, label: 'GP%' },
  { key: InvoiceFilterByEnumsKeys.account_number, value: InvoiceFilterByEnumsKeys.account_number, label: 'Customer Account Number' },
  { key: InvoiceFilterByEnumsKeys.customer, value: InvoiceFilterByEnumsKeys.customer, label: 'Customer' },
  { key: InvoiceFilterByEnumsKeys.client, value: InvoiceFilterByEnumsKeys.client, label: 'Client Name' },
  { key: InvoiceFilterByEnumsKeys.dispatch_number, value: InvoiceFilterByEnumsKeys.dispatch_number, label: 'Dispatch Number' },
  { key: InvoiceFilterByEnumsKeys.iso_number, value: InvoiceFilterByEnumsKeys.iso_number, label: 'ISO Number' },
  { key: InvoiceFilterByEnumsKeys.quote_number, value: InvoiceFilterByEnumsKeys.quote_number, label: 'Quote Number' },
  { key: InvoiceFilterByEnumsKeys.sales_team_id, value: InvoiceFilterByEnumsKeys.sales_team_id, label: 'Rep Code' },
];
