import fs from 'fs';
import path from 'path';
import logger from '@reactory/server-core/logging';
import ReactoryClientModel from '@reactory/server-modules/reactory-core/models/ReactoryClient';

export interface PublishClientEnvOptions {
  /**
   * The root folder of the PWA client project.
   * Resolved from process.env.REACTORY_CLIENT if not provided.
   */
  clientRoot?: string;
  /**
   * The target environment name used for the .env file suffix.
   * Defaults to 'local'.
   */
  target?: string;
  /**
   * Optional overrides passed through to each client's `toClientEnv` method.
   */
  envOptions?: {
    apiEndpoint?: string;
    cdnRoot?: string;
    port?: number;
    nodeEnv?: string;
  };
}

export interface PublishClientEnvResult {
  published: string[];
  failed: Array<{ key: string; error: Error }>;
}

/**
 * Reads all ReactoryClient documents from the database and writes a `.env.<target>`
 * file for each client into `<clientRoot>/config/env/<client.key>/`.
 *
 * The env file content is generated by the `toClientEnv()` instance method on the
 * ReactoryClient model which maps model fields to the REACT_APP_* variables expected
 * by the PWA client (see config/env/README.MD in the client project).
 *
 * This function is intended to be called during server startup when the
 * `REACTORY_CLIENT` environment variable points to the client project folder.
 */
export async function publishClientEnvFiles(
  options: PublishClientEnvOptions = {},
): Promise<PublishClientEnvResult> {
  const clientRoot = options.clientRoot || process.env.REACTORY_CLIENT;
  const target = options.target || process.env.REACTORY_CLIENT_ENV_TARGET || 'local';

  if (!clientRoot) {
    logger.debug(
      'REACTORY_CLIENT env variable is not set – skipping client env file publishing.',
    );
    return { published: [], failed: [] };
  }

  if (!fs.existsSync(clientRoot)) {
    logger.warn(
      `REACTORY_CLIENT points to "${clientRoot}" which does not exist – skipping client env file publishing.`,
    );
    return { published: [], failed: [] };
  }

  const envBaseDir = path.resolve(clientRoot, 'config', 'env');

  const clients = await ReactoryClientModel.find({}).exec();

  if (!clients || clients.length === 0) {
    logger.info('No ReactoryClient documents found – nothing to publish.');
    return { published: [], failed: [] };
  }

  const published: string[] = [];
  const failed: Array<{ key: string; error: Error }> = [];

  for (const client of clients) {
    try {
      const clientEnvDir = path.join(envBaseDir, client.key);

      // Ensure the directory exists
      if (!fs.existsSync(clientEnvDir)) {
        fs.mkdirSync(clientEnvDir, { recursive: true });
      }

      const envContent: string = (client as any).toClientEnv(options.envOptions);
      const envFilePath = path.join(clientEnvDir, `.env.${target}`);

      fs.writeFileSync(envFilePath, envContent, { encoding: 'utf-8' });

      logger.info(`Published env file for client "${client.key}" → ${envFilePath}`);
      published.push(client.key);
    } catch (err) {
      logger.error(`Failed to publish env file for client "${client.key}"`, err);
      failed.push({ key: client.key, error: err as Error });
    }
  }

  logger.info(
    `Client env publishing complete: ${published.length} succeeded, ${failed.length} failed.`,
  );

  return { published, failed };
}

export default publishClientEnvFiles;
