import fs from "fs";
import crypto from "crypto";
import path from "path";
import { cwd } from "process";
import Reactory from "@reactorynet/reactory-core";
import { ENVIRONMENT } from "@reactory/server-core/types/constants";
import { safeCDNUrl } from '@reactory/server-core/utils/url/safeUrl';

const util = require("util");
const exec = util.promisify(require("child_process").exec);

/**
 * Build a shell command prefix that sources nvm.sh so that `nvm use` works
 * inside non-interactive shells spawned by child_process.exec().
 *
 * Falls back to an empty prefix when NVM_DIR is unset or nvm.sh is missing,
 * which means the system-default node/npx/yarn will be used instead.
 */
const nvmPrefix = (): string => {
  const nvmDir = process.env.NVM_DIR || path.join(require("os").homedir(), ".nvm");
  const nvmSh = path.join(nvmDir, "nvm.sh");
  if (fs.existsSync(nvmSh)) {
    return `unset npm_config_prefix && source "${nvmSh}" && nvm use && `;
  }
  return "";
};

/**
 * Compute a SHA-1 checksum directly from a string buffer.
 * This avoids any file I/O race conditions by hashing in-memory data.
 */
const checksumFromString = (content: string, algo: string = "sha1"): string => {
  return crypto.createHash(algo).update(content, "utf8").digest("hex");
};

/**
 * Write a file durably using open/write/fsync/close to guarantee the data
 * is flushed to the filesystem before returning. Also ensures the parent
 * directory exists.
 */
const durableWriteFile = (filePath: string, content: string): void => {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  const fd = fs.openSync(filePath, "w");
  try {
    fs.writeSync(fd, content, 0, "utf8");
    fs.fsyncSync(fd);
  } finally {
    fs.closeSync(fd);
  }
};

/**
 * Safely delete a file if it exists. Handles concurrent deletion gracefully.
 */
const safeUnlink = (filePath: string): void => {
  try {
    fs.unlinkSync(filePath);
  } catch (err: any) {
    // ENOENT means the file is already gone -- that's fine
    if (err?.code !== "ENOENT") {
      throw err;
    }
  }
};

/**
 * Simple per-key async mutex to prevent concurrent compilations of the
 * same module. Each module id gets its own lock chain.
 */
const compileLocks = new Map<string, Promise<void>>();
const acquireCompileLock = (moduleId: string): { release: () => void; ready: Promise<void> } => {
  // Wait for any previous compilation of this module to finish
  const previous = compileLocks.get(moduleId) ?? Promise.resolve();
  let release: () => void;
  const gate = new Promise<void>((resolve) => { release = resolve; });
  compileLocks.set(moduleId, previous.then(() => gate));
  return { release: release!, ready: previous };
};

/**
 * Resolves the root directory for data/plugins storage, falling back gracefully
 * between APP_DATA_ROOT and REACTORY_DATA depending on host vs container environment.
 */
export const getDataRoot = (): string => {
  if (process.env.APP_DATA_ROOT && fs.existsSync(process.env.APP_DATA_ROOT)) {
    return process.env.APP_DATA_ROOT;
  }
  if (process.env.REACTORY_DATA && fs.existsSync(process.env.REACTORY_DATA)) {
    return process.env.REACTORY_DATA;
  }
  return process.env.APP_DATA_ROOT || process.env.REACTORY_DATA || path.join(process.cwd(), 'data');
};

/**
 * Service class that provides access to forms for the logged in user
 */

interface IRollupOptions {
  outputFile: string;
  inputFile: string;
  enviroment: string;
  moduleName: string;
}

const DefaultRollupOptions = (options: IRollupOptions) => `
/**
 * DO NOT EDIT THIS FILE, IT IS AUTO GENERATED AND WILL BE 
 * OVERWRITTEN EVERY TIME THE SOURCE PLUGIN FILE CHANGES
 **/
import { babel } from "@rollup/plugin-babel";
import commonjs from "@rollup/plugin-commonjs";
import resolve from "@rollup/plugin-node-resolve";
import replace from "@rollup/plugin-replace";
import typescript from '@rollup/plugin-typescript';

const jsx = require('rollup-plugin-jsx');


const NODE_ENV = process.env.NODE_ENV || "development";

export default {
  input: "${options.inputFile}",
  // 'external' is a top-level (input) option -- placing it under 'output'
  // is silently ignored by rollup and emits an "Unknown output options"
  // warning. Keeping react/react-dom external avoids inlining a copy of
  // React into every plugin bundle.
  external: ['react', 'react-dom'],
  output: {
    file: "${options.outputFile}",
    name: "${options.moduleName}",
    format: "umd",
    // 'globals' maps external module ids to the browser globals the UMD
    // wrapper reads them from. It must be an object, not an array.
    globals: {
      react: 'React',
      'react-dom': 'ReactDOM'
    },
    sourcemap: true
  },

  plugins: [
    replace({
      'process.env.NODE_ENV': JSON.stringify(NODE_ENV || "development"),
      preventAssignment: true
    }),
    commonjs({
      include: 'node_modules/**',
      exclude: [
        'node_modules/process-es6/**',
      ],   
    }),
    typescript({
      sourceMap: true
    }),        
    babel({
      exclude: 'node_modules/**',
      include: ['./src/**/*.ts', './src/**/*.js', './src/**/*.tsx'],
      babelHelpers: "bundled",
      sourceMaps: "both",
      extensions: ['.ts', '.tsx', '.js', '.jsx'],
      presets: [
        [
          "@babel/preset-env",
          {
            modules: false,
          }
        ],

        [
          "@babel/preset-react",          
        ],

        [
          "@babel/preset-typescript",          
        ]
      ],          
    }),
    jsx({ factory: 'React.createElement' }),
    resolve(),
  ],
};
`;

/**
 * Compiler options a module may declare via its `compilerOptions` field.
 *
 * `sourcePath` is the absolute path to the module's entry file on the server
 * source tree.  When present, the compiler resolves the module's local import
 * graph and copies every referenced local file into the module's runtime
 * folder so relative imports (./types, ../shared) resolve during bundling.
 */
interface IRollupCompilerOptions {
  sourcePath?: string;
}

/**
 * File extensions the import-graph walker will try when resolving a relative
 * import specifier to a file on disk, in priority order.
 */
const RESOLVABLE_EXTENSIONS = [".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".json"];

/** Extensions whose contents we parse for further relative imports. */
const CODE_EXTENSION_RE = /\.(ts|tsx|js|jsx|mjs|cjs)$/i;

/** Upper bound on files pulled into a single module bundle graph (runaway guard). */
const MAX_GRAPH_FILES = 500;

/**
 * Extract relative (./ or ../) import/export/require specifiers from a source
 * file.  Bare specifiers (react, @mui/..., @reactory/...) are intentionally
 * ignored -- those are resolved from node_modules / rollup externals and must
 * not be copied into the module folder.
 */
export const parseRelativeImports = (source: string): string[] => {
  const specifiers = new Set<string>();
  const patterns = [
    // import ... from './x'  AND  import './x'
    /\bimport\s+(?:[^'";]*?\sfrom\s+)?['"](\.[^'"]+)['"]/g,
    // export ... from './x'  AND  export * from './x'
    /\bexport\s+[^'";]*?\sfrom\s+['"](\.[^'"]+)['"]/g,
    // require('./x')
    /\brequire\(\s*['"](\.[^'"]+)['"]\s*\)/g,
    // import('./x')  (dynamic)
    /\bimport\(\s*['"](\.[^'"]+)['"]\s*\)/g,
  ];
  patterns.forEach((re) => {
    let match: RegExpExecArray | null;
    while ((match = re.exec(source)) !== null) {
      specifiers.add(match[1]);
    }
  });
  return Array.from(specifiers);
};

/**
 * Resolve a relative import specifier to an actual file on disk, trying the
 * common TypeScript/JavaScript extension and index-file conventions.  Returns
 * the absolute path, or null when nothing matches.
 */
export const resolveRelativeImport = (fromDir: string, specifier: string): string | null => {
  const base = path.resolve(fromDir, specifier);
  const candidates: string[] = [base];
  RESOLVABLE_EXTENSIONS.forEach((ext) => candidates.push(`${base}${ext}`));
  RESOLVABLE_EXTENSIONS.forEach((ext) => candidates.push(path.join(base, `index${ext}`)));
  for (const candidate of candidates) {
    try {
      if (fs.existsSync(candidate) && fs.statSync(candidate).isFile()) {
        return candidate;
      }
    } catch {
      /* ignore and keep trying */
    }
  }
  return null;
};

/**
 * Compute the deepest directory that is a common ancestor of every path
 * provided.  Used to preserve relative import structure when copying a
 * module's local file graph into its runtime folder.
 */
export const commonAncestorDir = (filePaths: string[]): string => {
  if (filePaths.length === 0) return "";
  const segmentLists = filePaths.map((p) => path.dirname(p).split(path.sep));
  const first = segmentLists[0];
  let commonLength = first.length;
  for (const segments of segmentLists.slice(1)) {
    let i = 0;
    while (i < commonLength && i < segments.length && segments[i] === first[i]) {
      i += 1;
    }
    commonLength = i;
  }
  return first.slice(0, commonLength).join(path.sep) || path.sep;
};

export interface IModuleFileGraph {
  /** Absolute source path -> file contents. */
  files: Map<string, string>;
  /** Absolute path of the entry file within the graph. */
  entry: string;
  /** Deepest common ancestor directory of all files in the graph. */
  baseDir: string;
  /** Relative import specifiers that could not be resolved to a file. */
  unresolved: string[];
}

/**
 * Walk the local (relative) import graph starting at an entry file and collect
 * every reachable local source file.  Bare / node_modules imports are
 * deliberately left out -- rollup resolves those separately.
 *
 * Returns null when the entry file itself cannot be read.
 */
export const buildModuleFileGraph = (entryPath: string): IModuleFileGraph | null => {
  const entry = path.resolve(entryPath);
  if (!fs.existsSync(entry)) return null;

  const files = new Map<string, string>();
  const unresolved: string[] = [];
  const queue: string[] = [entry];

  while (queue.length > 0 && files.size < MAX_GRAPH_FILES) {
    const current = path.resolve(queue.shift()!);
    if (files.has(current)) continue;

    let content: string;
    try {
      content = fs.readFileSync(current, "utf8");
    } catch {
      continue;
    }
    files.set(current, content);

    // Only follow imports out of code files -- .json / assets are leaves.
    if (!CODE_EXTENSION_RE.test(current)) continue;

    for (const specifier of parseRelativeImports(content)) {
      const resolved = resolveRelativeImport(path.dirname(current), specifier);
      if (resolved) {
        if (!files.has(path.resolve(resolved))) queue.push(resolved);
      } else {
        unresolved.push(`${specifier} (from ${current})`);
      }
    }
  }

  return {
    files,
    entry,
    baseDir: commonAncestorDir(Array.from(files.keys())),
    unresolved,
  };
};

/**
 * Compute a stable SHA-1 checksum across every file in a module graph.  The
 * relative path and content of each file are folded in (sorted by relative
 * path) so that a change to ANY included file -- not just the entry point --
 * triggers a recompile.
 */
export const checksumForGraph = (graph: IModuleFileGraph): string => {
  const entries = Array.from(graph.files.entries())
    .map(([abs, content]) => [path.relative(graph.baseDir, abs), content] as [string, string])
    .sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
  const hash = crypto.createHash("sha1");
  for (const [rel, content] of entries) {
    hash.update(rel);
    hash.update("\0");
    hash.update(content, "utf8");
    hash.update("\0");
  }
  return hash.digest("hex");
};

class ReactoryModuleCompilerService
  implements Reactory.Service.IReactoryModuleCompilerService
{
  name: string = "ReactoryModuleCompilerService";
  nameSpace: string = "core";
  version: string = "1.0.0";

  props: Reactory.Service.IReactoryServiceProps;
  context: Reactory.Server.IReactoryContext;

  fileService: Reactory.Service.IReactoryFileService;

  constructor(
    props: Reactory.Service.IReactoryServiceProps,
    context: Reactory.Server.IReactoryContext
  ) {
    this.props = props;
    this.context = context;
  }

  /**
   * These should only be called during development, and should not be used in production.
   * Compiled resources should be stored in a CDN and served from there.
   * @param module
   * @returns
   */
  async compileModule(
    module: Reactory.Forms.IReactoryFormModule
  ): Promise<Reactory.Forms.IReactoryFormResource> {
    const dataRoot = getDataRoot();
    const runtimeBase = path.join(dataRoot, "plugins", "__runtime__");
    const compiledFile = path.join(runtimeBase, `lib/${module.id}.min.js`);

    // ---------------------------------------------------------------
    // Acquire a per-module lock so concurrent requests for the same
    // module are serialised.  This prevents one call's cleanup from
    // deleting files another call is still reading.
    // ---------------------------------------------------------------
    const lock = acquireCompileLock(module.id);
    await lock.ready;

    try {
      return await this.doCompileModule(module, runtimeBase, compiledFile);
    } catch (fatalError) {
      this.context.log(
        `Fatal error compiling module ${module.id}`,
        { fatalError },
        "error",
        ReactoryModuleCompilerService.reactory.id
      );
      return this.createFailureResource(module, compiledFile, "Unexpected compilation error");
    } finally {
      lock.release();
    }
  }

  /**
   * Internal compilation logic, called under the per-module lock.
   *
   * Each module is bundled from its own folder under `src/<module-id>/`.  When
   * the module declares a `sourcePath` in its compilerOptions, the entry file's
   * local import graph is resolved and every referenced local file is copied
   * into that folder (mirroring the original relative layout) so imports like
   * `./types` or `../shared/util` resolve during bundling.  Modules without a
   * sourcePath fall back to a single entry file synthesised from `module.src`.
   */
  private async doCompileModule(
    module: Reactory.Forms.IReactoryFormModule,
    runtimeBase: string,
    compiledFile: string,
  ): Promise<Reactory.Forms.IReactoryFormResource> {
    const that = this;

    const opts = (module.compilerOptions ?? {}) as IRollupCompilerOptions;
    // The '@' in a module id is a valid directory-name character; only path
    // separators need neutralising so the id maps to a single folder.
    const moduleDirName = module.id.replace(/[\\/]/g, "_");
    const moduleDir = path.join(runtimeBase, "src", moduleDirName);
    const checksumFile = path.join(moduleDir, ".reactory-checksum");
    const fileType = module.fileType || "tsx";

    // ---------------------------------------------------------------
    // Resolve the set of files that make up this module.  With a
    // sourcePath we walk the local import graph; otherwise we fall back
    // to a single inline entry file from module.src.
    // ---------------------------------------------------------------
    let graph: IModuleFileGraph | null = null;
    if (opts.sourcePath) {
      graph = buildModuleFileGraph(opts.sourcePath);
      if (!graph) {
        this.context.log(
          `sourcePath for module ${module.id} could not be read (${opts.sourcePath}); falling back to inline src`,
          { sourcePath: opts.sourcePath },
          "warning",
          ReactoryModuleCompilerService.reactory.id,
        );
      } else if (graph.unresolved.length > 0) {
        this.context.log(
          `Some relative imports for module ${module.id} could not be resolved to files`,
          { unresolved: graph.unresolved },
          "warning",
          ReactoryModuleCompilerService.reactory.id,
        );
      }
    }

    let entryRelative: string;
    const filesToWrite: Array<{ relative: string; content: string }> = [];
    let newChecksum: string;

    if (graph) {
      entryRelative = path.relative(graph.baseDir, graph.entry);
      for (const [abs, content] of graph.files.entries()) {
        filesToWrite.push({ relative: path.relative(graph.baseDir, abs), content });
      }
      newChecksum = checksumForGraph(graph);
    } else {
      entryRelative = `entry.${fileType}`;
      filesToWrite.push({ relative: entryRelative, content: module.src });
      newChecksum = checksumFromString(module.src, "sha1");
    }

    const entryFile = path.join(moduleDir, entryRelative);

    // ---------------------------------------------------------------
    // Decide whether a recompile is needed.  The stored checksum covers
    // every file in the graph, so a change to any include (not just the
    // entry) triggers a rebuild.
    // ---------------------------------------------------------------
    let doCompile = false;
    if (!fs.existsSync(compiledFile) || !fs.existsSync(entryFile)) {
      doCompile = true;
    } else {
      let existingChecksum = "";
      try {
        if (fs.existsSync(checksumFile)) {
          existingChecksum = fs.readFileSync(checksumFile, "utf8").trim();
        }
      } catch (checksumErr) {
        this.context.log(
          `Could not read checksum for module ${module.id}, will recompile`,
          { checksumErr },
          "warning",
          ReactoryModuleCompilerService.reactory.id,
        );
        existingChecksum = "";
      }
      if (existingChecksum !== newChecksum) {
        doCompile = true;
      }
    }

    // ---------------------------------------------------------------
    // Compile with rollup if the source has changed
    // ---------------------------------------------------------------
    if (doCompile) {
      const result = await this.compileWithRollup(
        module,
        moduleDir,
        entryFile,
        filesToWrite,
        compiledFile,
        runtimeBase,
      );

      if (result.success) {
        try {
          durableWriteFile(checksumFile, newChecksum);
        } catch (writeErr) {
          that.context.log(
            `Failed to persist checksum for module ${module.id}`,
            { writeErr },
            "warning",
            ReactoryModuleCompilerService.reactory.id,
          );
        }
      } else {
        const notification = `$reactory.createNotification("Compilation error on module ${module.id}, see console log for details", { type: 'warning' });`;
        const errorLogs = result.messages.map((msg) => {
          that.context.log("Error compiling module", { message: msg }, "error");
          return `$reactory.log("Compilation Failure for ${module.id} --> [${msg}]", { module: ${JSON.stringify(module)} }, 'error');`;
        });

        const failureScript = `
          if(window && window.reactory) {
            var $reactory = window.reactory.api;
            ${notification}
            ${errorLogs.join("\n")}
          }
        `;

        try {
          durableWriteFile(compiledFile, failureScript);
        } catch (writeErr) {
          that.context.log(
            `Failed to write failure script for module ${module.id}`,
            { writeErr },
            "error",
            ReactoryModuleCompilerService.reactory.id
          );
        }
      }
    }

    return {
      name: module.id,
      type: "script",
      uri: safeCDNUrl(`plugins/__runtime__/lib/${module.id}.min.js?cs=${newChecksum}`),
      id: module.id,
      signature: newChecksum,
      signatureMethod: "sha1",
      crossOrigin: false,
      signed: true,
      expr: "",
      required: true,
      cacheProvider: "CDN",
    };
  }

  /**
   * Run rollup to bundle a module from its own runtime folder.
   *
   * The module folder is wiped and rewritten on every compile so stale
   * includes from a previous build (e.g. an import that was since removed)
   * never linger.  Uses durableWriteFile to guarantee the source files and
   * config are fully flushed to disk before rollup is spawned.
   */
  private async compileWithRollup(
    module: Reactory.Forms.IReactoryFormModule,
    moduleDir: string,
    entryFile: string,
    filesToWrite: Array<{ relative: string; content: string }>,
    compiledFile: string,
    runtimeBase: string,
  ): Promise<{ success: boolean; messages: string[] }> {
    const result = { success: false, messages: [] as string[] };

    // Start from a clean module folder so removed includes do not persist.
    try {
      if (fs.existsSync(moduleDir)) {
        fs.rmSync(moduleDir, { recursive: true, force: true });
      }
    } catch (rmErr) {
      this.context.log(
        `Could not clean module folder for ${module.id}`,
        { rmErr, moduleDir },
        "warning",
        ReactoryModuleCompilerService.reactory.id,
      );
    }
    fs.mkdirSync(moduleDir, { recursive: true });

    // Write the entry file plus every resolved local include, preserving
    // their relative layout (open → write → fsync → close per file).
    filesToWrite.forEach((file) => {
      durableWriteFile(path.join(moduleDir, file.relative), file.content);
    });

    const $config = DefaultRollupOptions({
      enviroment: process.env.NODE_ENV || "development",
      inputFile: entryFile,
      outputFile: compiledFile,
      moduleName: `reactory-plugin-${module.id
        .replace(".", "-")
        .replace("@", "-")}`,
    });

    const rollupConfigFile = path.join(runtimeBase, `rollup.${module.id}.js`);
    durableWriteFile(rollupConfigFile, $config);

    try {
      const { stdout, stderr, error } = await exec(
        `${nvmPrefix()} ./build.sh rollup.${module.id}.js`,
        { cwd: runtimeBase, encoding: "utf8", shell: "/bin/bash" },
      );

      this.context.log(
        `Compiled resource ${module.id}`,
        { stdout, stderr, error },
        "debug",
        ReactoryModuleCompilerService.reactory.id,
      );

      if (fs.existsSync(compiledFile)) {
        result.success = true;
      } else {
        result.messages.push(stderr || stdout || "rollup produced no output");
      }
    } catch (execErr: any) {
      this.context.log(
        `Error executing rollup for module ${module.id}`,
        { execErr },
        "error",
        ReactoryModuleCompilerService.reactory.id,
      );
      result.messages.push(execErr?.stderr || execErr?.message || String(execErr));
    }

    return result;
  }

  /**
   * Creates a failure resource when compilation fails.
   * Returns a valid resource object that displays an error notification
   * in the browser, ensuring the service always returns a response.
   */
  private createFailureResource(
    module: Reactory.Forms.IReactoryFormModule,
    compiledFile: string,
    errorMessage: string,
  ): Reactory.Forms.IReactoryFormResource {
    const failureScript = `
      if(window && window.reactory) {
        var $reactory = window.reactory.api;
        $reactory.createNotification("Compilation error on module ${module.id}: ${errorMessage}", { type: 'error' });
        $reactory.log("Compilation Failure for ${module.id} --> [${errorMessage}]", { module: "${module.id}" }, 'error');
      }
    `;

    try {
      durableWriteFile(compiledFile, failureScript);
    } catch (writeErr) {
      this.context.log(
        `Could not write failure script for module ${module.id}`,
        { writeErr, compiledFile },
        "error",
        ReactoryModuleCompilerService.reactory.id,
      );
    }

    return {
      name: module.id,
      type: "script",
      uri: safeCDNUrl(`plugins/__runtime__/lib/${module.id}.min.js?error=true`),
      id: module.id,
      signature: "",
      signatureMethod: "sha1",
      crossOrigin: false,
      signed: false,
      expr: "",
      required: true,
      cacheProvider: "CDN",
    };
  }

  async onStartup(): Promise<any> {
    const dataRoot = getDataRoot();
    const runtimePath = path.join(
      dataRoot,
      "plugins",
      "__runtime__"
    );
    const libPath = path.join(
      dataRoot,
      "plugins",
      "__runtime__",
      "lib"
    );
    const srcPath = path.join(
      dataRoot,
      "plugins",
      "__runtime__",
      "src"
    );

    if (!fs.existsSync(runtimePath)) {
      fs.mkdirSync(runtimePath, { recursive: true });
      const files = [
        ".jshintrc",
        ".nvmrc",
        "tsconfig.template.json",
        "package.template.json",
      ];
      this.context.log(
        "Copying runtime files",
        { files },
        "debug",
        ReactoryModuleCompilerService.reactory.id
      );
      const assetsFolder = path.join(
        cwd(),
        `${process.env.APPLICATION_ROOT}/modules/reactory-core/services/assets/RuntimePluginsProject`
      );
      files.forEach((file) => {
        fs.copyFileSync(
          path.join(assetsFolder, file),
          path.join(runtimePath, file)
        );
      });

      try {
        // rename the package.json and tsconfig.json
        fs.renameSync(
          path.join(runtimePath, "package.template.json"),
          path.join(runtimePath, "package.json")
        );
        fs.renameSync(
          path.join(runtimePath, "tsconfig.template.json"),
          path.join(runtimePath, "tsconfig.json")
        );
      } catch (renameException) {
        this.context.log(
          "Error renaming files",
          { renameException },
          "error",
          ReactoryModuleCompilerService.reactory.id
        );
      }

      //run yarn install in the runtime folder
      this.context.log(
        "Running yarn Install - this may take ~3 - 5 minutes depending on your connection",
        { runtimePath },
        "debug",
        ReactoryModuleCompilerService.reactory.id
      );
      const { stdout, stderr } = await exec(`${nvmPrefix()}yarn install`, {
        cwd: runtimePath,
        shell: "/bin/bash",
      });

      if (stdout.length > 0)
        this.context.log(
          `Yarn Install stdout`,
          { stdout },
          "debug",
          ReactoryModuleCompilerService.reactory.id
        );
      if (stderr.length > 0)
        this.context.log(
          `NPM Install stderr`,
          { stderr },
          "debug",
          ReactoryModuleCompilerService.reactory.id
        );
    }
    if (!fs.existsSync(libPath)) fs.mkdirSync(libPath, { recursive: true });
    if (!fs.existsSync(srcPath)) fs.mkdirSync(srcPath, { recursive: true });

    return true;
  }

  getExecutionContext(): Reactory.Server.IReactoryContext {
    return this.context;
  }

  setExecutionContext(context: Reactory.Server.IReactoryContext): boolean {
    this.context = context;
    return true;
  }

  setFileService(fileService: Reactory.Service.IReactoryFileService) {
    this.fileService = fileService;
  }

  static reactory: Reactory.Service.IReactoryServiceDefinition<ReactoryModuleCompilerService> =
    {
      id: "core.ReactoryModuleCompilerService@1.0.0",
      nameSpace: "core",
      description: "Reactory Module Compiler Service",
      name: "ReactoryModuleCompilerService",
      service: (props, context) => {
        return new ReactoryModuleCompilerService(props, context);
      },
      dependencies: [
        {
          id: "core.ReactoryFileService@1.0.0",
          alias: "fileService",
        },
      ],
    };
}

export default ReactoryModuleCompilerService;
